// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dmdservice.proto

package medicine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MedicationString struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MedicationString) Reset()         { *m = MedicationString{} }
func (m *MedicationString) String() string { return proto.CompactTextString(m) }
func (*MedicationString) ProtoMessage()    {}
func (*MedicationString) Descriptor() ([]byte, []int) {
	return fileDescriptor_408d3256f55e7040, []int{0}
}

func (m *MedicationString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MedicationString.Unmarshal(m, b)
}
func (m *MedicationString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MedicationString.Marshal(b, m, deterministic)
}
func (m *MedicationString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MedicationString.Merge(m, src)
}
func (m *MedicationString) XXX_Size() int {
	return xxx_messageInfo_MedicationString.Size(m)
}
func (m *MedicationString) XXX_DiscardUnknown() {
	xxx_messageInfo_MedicationString.DiscardUnknown(m)
}

var xxx_messageInfo_MedicationString proto.InternalMessageInfo

func (m *MedicationString) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func init() {
	proto.RegisterType((*MedicationString)(nil), "medicine.MedicationString")
}

func init() { proto.RegisterFile("dmdservice.proto", fileDescriptor_408d3256f55e7040) }

var fileDescriptor_408d3256f55e7040 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xc9, 0x4d, 0x29,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xc8, 0x4d,
	0x4d, 0xc9, 0x4c, 0xce, 0xcc, 0x4b, 0x95, 0xe2, 0x83, 0xb1, 0x20, 0x32, 0x52, 0x32, 0xe9, 0xf9,
	0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa, 0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25,
	0x99, 0xf9, 0x79, 0xc5, 0x10, 0x59, 0x25, 0x05, 0x2e, 0x01, 0x5f, 0x90, 0x7a, 0xb0, 0x60, 0x70,
	0x49, 0x51, 0x66, 0x5e, 0xba, 0x10, 0x0f, 0x17, 0x63, 0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67,
	0x10, 0x63, 0xb1, 0x51, 0x1e, 0x17, 0x73, 0x4a, 0x6e, 0x8a, 0x50, 0x3a, 0x17, 0x7f, 0x40, 0x62,
	0x51, 0x71, 0x2a, 0x42, 0xb5, 0x90, 0x94, 0x1e, 0xdc, 0x2a, 0x74, 0x33, 0xa4, 0x90, 0xe4, 0xc0,
	0xda, 0x52, 0x10, 0x2a, 0x94, 0x64, 0x9a, 0x2e, 0x3f, 0x99, 0xcc, 0x24, 0x26, 0x24, 0xa2, 0x5f,
	0x66, 0xa8, 0x5f, 0x9c, 0x97, 0x9f, 0x9b, 0x9a, 0xa2, 0x9f, 0x92, 0x9b, 0xa2, 0x5f, 0x00, 0x52,
	0xe8, 0xc4, 0x15, 0x05, 0xf7, 0x4b, 0x12, 0x1b, 0xd8, 0x91, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xa0, 0x34, 0x5d, 0x09, 0xf0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DmdClient is the client API for Dmd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DmdClient interface {
	ParseMedication(ctx context.Context, in *MedicationString, opts ...grpc.CallOption) (*ParsedMedication, error)
}

type dmdClient struct {
	cc *grpc.ClientConn
}

func NewDmdClient(cc *grpc.ClientConn) DmdClient {
	return &dmdClient{cc}
}

func (c *dmdClient) ParseMedication(ctx context.Context, in *MedicationString, opts ...grpc.CallOption) (*ParsedMedication, error) {
	out := new(ParsedMedication)
	err := c.cc.Invoke(ctx, "/medicine.dmd/ParseMedication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DmdServer is the server API for Dmd service.
type DmdServer interface {
	ParseMedication(context.Context, *MedicationString) (*ParsedMedication, error)
}

func RegisterDmdServer(s *grpc.Server, srv DmdServer) {
	s.RegisterService(&_Dmd_serviceDesc, srv)
}

func _Dmd_ParseMedication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MedicationString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DmdServer).ParseMedication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/medicine.dmd/ParseMedication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DmdServer).ParseMedication(ctx, req.(*MedicationString))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dmd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "medicine.dmd",
	HandlerType: (*DmdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseMedication",
			Handler:    _Dmd_ParseMedication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dmdservice.proto",
}
